# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rego', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('status_reason', models.CharField(max_length=1000)),
                ('status_contact_name', models.CharField(max_length=100)),
                ('status_contact_email', models.CharField(max_length=100)),
                ('status_contact_phone', models.CharField(max_length=100)),
                ('status_from_time', models.DateTimeField()),
                ('status_to_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('pax_instructor', models.CharField(max_length=100)),
                ('pilot_student', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crac_booking.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cell_phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
