# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crac_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('from_time',)},
        ),
        migrations.AddField(
            model_name='importedbooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crac_booking.Booking'),
        ),
    ]
