# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crac_booking', '0004_auto_20180516_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hobs_end',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hobs_start',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
