# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crac_booking', '0005_auto_20181009_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hobs_end',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hobs_start',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
